## Where 函数(创建新数组) 

In [1]:
import numpy as np
a=np.random.randint(100,200,(4,6))
a

array([[134, 157, 191, 148, 164, 103],
       [136, 169, 152, 176, 143, 152],
       [190, 144, 149, 141, 125, 148],
       [111, 166, 112, 155, 127, 179]])

### 用Where替换数值 

In [2]:
np.where(a>160,'合格',0)

array([['0', '0', '合格', '0', '合格', '0'],
       ['0', '合格', '0', '合格', '0', '0'],
       ['合格', '0', '0', '0', '0', '0'],
       ['0', '合格', '0', '0', '0', '合格']], dtype='<U11')

### 用Where  定位后实现运算

In [5]:
np.where(a>160,a*100,a*10)

array([[ 1430,  1040, 16500, 18000,  1130,  1470],
       [19300, 19700,  1320, 17900,  1350, 17900],
       [ 1160, 18500, 18900, 19400, 18700,  1430],
       [17800,  1240, 16800, 19200,  1550, 19500]])

### Where 的机制: 可应用广播机制
    (第一个参数为判断参数,第二个参数为数组,第三个参数也为数组)
    运算原理,根据定位判断,正确返回第二个数组里对应的值,否则就返回第三个参数数组里对应值.
        如果第二和第三参数为一个值时候,应用广播机制当作是数组执行)

### 应用Where机制 实践

In [7]:
np.where(a>150,[1,2,3,4,5,6],0)

array([[0, 0, 3, 4, 0, 0],
       [1, 2, 0, 4, 0, 6],
       [0, 2, 3, 4, 5, 0],
       [1, 0, 3, 4, 5, 6]])

### Where 符合替换,不符合不变

In [8]:
np.where(a>150,'你是对的',a)

array([['143', '104', '你是对的', '你是对的', '113', '147'],
       ['你是对的', '你是对的', '132', '你是对的', '135', '你是对的'],
       ['116', '你是对的', '你是对的', '你是对的', '你是对的', '143'],
       ['你是对的', '124', '你是对的', '你是对的', '你是对的', '你是对的']], dtype='<U11')

### Where 判断后返回下标结果 

In [9]:
np.where(a>150)

(array([0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int64),
 array([2, 3, 0, 1, 3, 5, 1, 2, 3, 4, 0, 2, 3, 4, 5], dtype=int64))

#### 其中第一行是0维下标,第二行是1维下标 

### 用zip组合坐标,得到完整坐标列表 

In [13]:
s=np.where(a>150)
xy=list(zip(s[0],s[1]))
xy

[(0, 2),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 3),
 (1, 5),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (3, 0),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5)]