In [2]:
import numpy as np

In [9]:
x=np.random.randint(1,99,(3,5))
x

array([[68, 26, 44, 65, 47],
       [75, 38, 65, 19, 66],
       [ 6, 42, 54, 56, 50]])

## 花式索引使用方法
    x[[行坐标列表],[列坐标列表]]

In [10]:
x[[1,2],[3,4]]

array([19, 50])

##  广播机制的 花式索引方法
    x[[行坐标列表],数字a] ,其中 数字a 可以被广播

### 意思就是可以取出 行坐标里的 所有 数字a 列的数字

In [11]:
x[[1,2],3]

array([19, 56])

### 利用广播机制 提取不连续列

In [18]:
x[:,[1,2,4]]

array([[26, 44, 47],
       [38, 65, 66],
       [42, 54, 50]])

## 利用广播机制 提取交叉行列数据

### 提取的是第0行,1行,所有1,3,4列的数据

In [19]:
x[[[0],[1]],[1,3,4]]

array([[26, 65, 47],
       [38, 19, 66]])

## 实例  
### 按条件提取指定列所有数据

#### 算出月销量

In [20]:
月销量=np.sum(x,axis=0)
月销量

array([149, 106, 163, 140, 163])

#### 找出符合条件列

In [23]:
列号=np.where(月销量<141)
列号

(array([1, 3], dtype=int64),)

#### 从元组里提取列号 

In [25]:
列号[0]

array([1, 3], dtype=int64)

####  用花式索引提取结果

In [26]:
x[:,列号[0]]

array([[26, 65],
       [38, 19],
       [42, 56]])