###     读取 火焰纹章角色数据-4，使用 KNeighborsClassifier 分类器与训练集，推断未知角色“辛格尔德”的职业。

In [87]:
import pandas as pd
pd.set_option('display.max_rows', 20)
sh=pd.read_excel(r'C:\Users\YcAllenEffy\Desktop\fire_emblem_4.xlsx',engine='openpyxl',sheet_name=0)
df_src=sh.copy()
df_src

角色   职业  HP  力量  魔力  技巧  速度  幸运  防守  魔防  魅力  行动点
0   艾黛尔贾特   剑客  20   7   3   6   6   4   5   2   0    4
1    帝弥托利   士兵  20   8   3   6   6   4   5   2   0    4
2     库罗德   战士  20   8   3   6   6   4   5   2   0    4
3     修伯特  修道士  20   4   8   6   6   4   3   4   0    4
4   菲尔迪南特   领主  25   9   6  10  10   8   6   3   0    5
..    ...  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...
61     尼诺   盗贼  25   9   6  11  11   8   6   2   0    5
62    加法尔  重骑士  30   9   6   7   4   8  12   1   0    4
63    瓦依达   佣兵  25   9   6  10  10   8   6   2   0    5
64    莱那特   盗贼  25   9   6  11  11   8   6   2   0    5
65    阿特斯   佣兵  25   9   6  10  10   8   6   2   0    5

[66 rows x 12 columns]

In [88]:
import pandas as pd
pd.set_option('display.max_rows', 20)
sh=pd.read_excel(r'C:\Users\YcAllenEffy\Desktop\fire_emblem_4.xlsx',engine='openpyxl',sheet_name=1)
df_ans=sh.copy()
df_ans

角色  职业  HP  力量  魔力  技巧  速度  幸运  防守  魔防  魅力  行动点
0  辛格尔德  未知  30  10   6   6   5   8  12   2   0    5

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier as KNN

In [89]:
# 分类器
df_train,df_test=train_test_split(df_src,test_size=0.2,random_state=42)

In [90]:
# 模型设置
knn=KNN()
x=df_train.iloc[:,2:]
y=df_train['职业']

In [92]:
# 循环预测,优化k值
for i in range(20):
# 模型初始化
    knn.n_neighbors=i+1
    model=knn.fit(x,y)
#预测
    y_predict=model.predict(df_test.iloc[:,2:])
    print(knn.n_neighbors,accuracy_score(df_test['职业'],y_predict))

1 1.0
2 0.7857142857142857
3 0.7857142857142857
4 0.7857142857142857
5 0.7857142857142857
6 0.7142857142857143
7 0.7142857142857143
8 0.7142857142857143
9 0.7142857142857143
10 0.7142857142857143
11 0.7142857142857143
12 0.6428571428571429
13 0.6428571428571429
14 0.6428571428571429
15 0.6428571428571429
16 0.6428571428571429
17 0.6428571428571429
18 0.6428571428571429
19 0.6428571428571429
20 0.6428571428571429


In [93]:
# 实践结果
knn.n_neighbors=1
model=knn.fit(x,y)
ans_test=model.predict(df_ans.iloc[:,2:])
ans_test

array(['重骑士'], dtype=object)

In [28]:
# 标准答案
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 导入数据
file = r'C:\Users\YcAllenEffy\Desktop\fire_emblem_4.xlsx'
df_src = pd.read_excel(file, sheet_name=0)      # 已知数据
df_unknown = pd.read_excel(file, sheet_name=1)  # 未知数据

# 将已知数据拆分为训练集和测试集
df_train, df_test = train_test_split( df_src, test_size=0.2, random_state=42 )

# 用训练集训练模型，用测试集测试并得到最高准确率的K值
x = df_train.iloc[:, 2:12]
y = df_train['职业']

for k in range(1, 20, 2):
    knn = KNeighborsClassifier(n_neighbors = k)
    model = knn.fit(x, y)
    # 对测试集进行预测，求准确率
    y_predict = model.predict( df_test.iloc[:, 2:12] )
    acc = accuracy_score( df_test['职业'], y_predict )
    print( f'当K值是{k}时，预测准确率是 {acc}' )

# 设置最高准确率的K值，重新训练，预测未知数据
knn.n_neighbors = 1
model = knn.fit(x, y)
res = model.predict( df_unknown.iloc[ :, 2:12 ] )[0]
print('辛格尔德的职业是：', res)

当K值是1时，预测准确率是 1.0
当K值是3时，预测准确率是 0.7857142857142857
当K值是5时，预测准确率是 0.7857142857142857
当K值是7时，预测准确率是 0.7142857142857143
当K值是9时，预测准确率是 0.7142857142857143
当K值是11时，预测准确率是 0.7142857142857143
当K值是13时，预测准确率是 0.6428571428571429
当K值是15时，预测准确率是 0.6428571428571429
当K值是17时，预测准确率是 0.6428571428571429
当K值是19时，预测准确率是 0.6428571428571429
辛格尔德的职业是： 重骑士


###   读取 火焰纹章角色数据-5，使用 KNeighborsClassifier 分类器与训练集，预测未知角色“瓦尔基里”的速度。

In [52]:
import pandas as pd
pd.set_option('display.max_rows', 20)
sh=pd.read_excel(r'C:\Users\YcAllenEffy\Desktop\fire_emblem_5.xlsx',engine='openpyxl',sheet_name=0)
df_src=sh.copy()
df_src

角色   职业  HP  力量  魔力  技巧  幸运  防守  魔防  魅力  行动点  速度
0   艾黛尔贾特   剑客  20   7   3   6   4   5   2   0    4   6
1    帝弥托利   士兵  20   8   3   6   4   5   2   0    4   6
2     库罗德   战士  20   8   3   6   4   5   2   0    4   6
3     修伯特  修道士  20   4   8   6   4   3   4   0    4   6
4   菲尔迪南特   领主  25   9   6  10   8   6   3   0    5  10
..    ...  ...  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..
61     尼诺   盗贼  25   9   6  11   8   6   2   0    5  11
62    加法尔  重骑士  30   9   6   7   8  12   1   0    4   4
63    瓦依达   佣兵  25   9   6  10   8   6   2   0    5  10
64    莱那特   盗贼  25   9   6  11   8   6   2   0    5  11
65    阿特斯   佣兵  25   9   6  10   8   6   2   0    5  10

[66 rows x 12 columns]

In [53]:
import pandas as pd
pd.set_option('display.max_rows', 20)
sh=pd.read_excel(r'C:\Users\YcAllenEffy\Desktop\fire_emblem_5.xlsx',engine='openpyxl',sheet_name=1)
df_ans=sh.copy()
df_ans

角色  职业  HP  力量  魔力  技巧  幸运  防守  魔防  魅力  行动点  速度
0  瓦尔基里  未知  22   4   7   5   4   3   4   0    4  未知

In [66]:
# 分类器
df_train,df_test=train_test_split(df_src,test_size=0.2,random_state=42)

In [84]:
# 模型
knn=KNN(n_neighbors=6)

x=df_train.iloc[:,2:-1]
y=df_train['速度']

In [85]:
# 循环预测,优化k值
for k in range(1,10):
# 模型初始化
    knn.n_neighbors=k
    model=knn.fit(x,y)
#预测
    y_predict=model.predict(df_test.iloc[:,2:-1])
    print(knn.n_neighbors,accuracy_score( df_test['速度'], y_predict ))

1 1.0
2 1.0
3 0.7142857142857143
4 0.7142857142857143
5 0.7142857142857143
6 0.7142857142857143
7 0.7142857142857143
8 0.7142857142857143
9 0.7142857142857143


In [86]:
# 实践结果
knn.n_neighbors=1
model=knn.fit(x,y)
ans_test=model.predict(df_ans.iloc[:,2:-1])
ans_test[0]

6

In [77]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 导入数据
file = r'C:\Users\YcAllenEffy\Desktop\fire_emblem_5.xlsx'
df_src = pd.read_excel(file, sheet_name=0)      # 已知数据
df_unknown = pd.read_excel(file, sheet_name=1)  # 未知数据

# 将已知数据拆分为训练集和测试集
df_train, df_test = train_test_split( df_src, test_size=0.2, random_state=66 )

# 用训练集训练模型，用测试集测试并得到最高准确率的K值
x = df_train.iloc[:, 2:11]
y = df_train['速度']

for k in range(1, 10, 2):
    knn = KNeighborsClassifier(n_neighbors = k)
    model = knn.fit(x, y)
    # 对测试集进行预测，求准确率
    y_predict = model.predict( df_test.iloc[:, 2:11] )
    print(y_predict)
    acc = accuracy_score( df_test['速度'], y_predict )
    print( f'当K值是{k}时，预测准确率是 {acc}' )

knn.n_neighbors = 1
model = knn.fit(x, y)
res = model.predict( df_unknown.iloc[ :, 2:11 ] )[0]
print('瓦尔基里的速度是：', res)

[ 6 11 10  6  6  6 10 11 11 11  6 10  6 10]
当K值是1时，预测准确率是 1.0
[10 11 10 10 10  6 10 11 11 11  6 10 10 10]
当K值是3时，预测准确率是 0.7142857142857143
[10 11 10 10 10  6 10 11 11 11  6 10 10 10]
当K值是5时，预测准确率是 0.7142857142857143
[10 11 10 10 10  6 10 11 11 11  6 10 10 10]
当K值是7时，预测准确率是 0.7142857142857143
[10 11 10 10 10  6 10 11 11 11  6 10 10 10]
当K值是9时，预测准确率是 0.7142857142857143
瓦尔基里的速度是： 6
