### 整体运算

  nd*5

  测试循环语句与整体运算速度比较

#### 通用函数运算

  np.abs()

  np.round(x,2) 2表示保留2位小数

  np.round(x,out=y)out参数表示将结果写入y中,其中y可以是切片y[::2]

  np.add.reduce(x) 累加

#### 对位计算(同形数组)

  x+x2

#### 点积:

  原理:左边每行 逐个乘以 右边每列 对应数值 并累加,(其中左列个数等于右行个数)

  实践:nd.dot(nd2) nd与nd2点积

In [1]:
import numpy as np
import pandas as pd

In [4]:
nd=np.random.randint(-100,100,10)
nd

array([-85, -71,  12,   5, -51, -31, -54, -36, -63, -67])

In [5]:
nd*2

array([-170, -142,   24,   10, -102,  -62, -108,  -72, -126, -134])

### 通用函数运算

In [6]:
np.abs(nd)

array([85, 71, 12,  5, 51, 31, 54, 36, 63, 67])

In [7]:
nd2=np.random.rand(3,5)
nd2

array([[0.17557081, 0.45601972, 0.39872424, 0.63185579, 0.97963561],
       [0.2454881 , 0.18612286, 0.45552718, 0.46972412, 0.78951978],
       [0.89651444, 0.01709643, 0.33384442, 0.03257399, 0.29854739]])

In [9]:
np.round(nd2,2)

array([[0.18, 0.46, 0.4 , 0.63, 0.98],
       [0.25, 0.19, 0.46, 0.47, 0.79],
       [0.9 , 0.02, 0.33, 0.03, 0.3 ]])

In [33]:

y=np.random.rand(3,5)
y

array([[0.92187178, 0.47040348, 0.71496546, 0.21646093, 0.76877481],
       [0.05936239, 0.46969185, 0.71580824, 0.07503654, 0.95596203],
       [0.62688642, 0.26756567, 0.72554291, 0.25063348, 0.74666926]])

In [34]:
np.round(nd2,2,out=y[::1])

array([[0.18, 0.46, 0.4 , 0.63, 0.98],
       [0.25, 0.19, 0.46, 0.47, 0.79],
       [0.9 , 0.02, 0.33, 0.03, 0.3 ]])

In [15]:
np.add.reduce(nd)

-441

### 对位运算,同形数组

In [35]:
x=np.random.randint(0,200,(3,4))
x2=np.random.randint(0,200,(3,4))

In [37]:
x

array([[ 45,  60, 163,  88],
       [ 15, 163,  84, 189],
       [ 13,   9, 134,  13]])

In [38]:
x2

array([[182, 197, 173, 168],
       [114,  21,  81, 180],
       [156, 180, 167,  53]])

In [36]:
x+x2

array([[227, 257, 336, 256],
       [129, 184, 165, 369],
       [169, 189, 301,  66]])

### 点积

In [55]:
x=np.random.randint(0,10,(2,3))
x2=np.random.randint(0,10,(3,5))

In [56]:
x

array([[1, 3, 7],
       [7, 2, 0]])

In [57]:
x2

array([[1, 5, 9, 4, 8],
       [0, 2, 4, 3, 7],
       [5, 1, 9, 1, 9]])

In [58]:
x.dot(x2)

array([[36, 18, 84, 20, 92],
       [ 7, 39, 71, 34, 70]])