In [1]:
import numpy as np

# 数组维度的理解 

## 3x2x4
### 创建三维 数组 3组2行4列 

In [2]:
a=np.random.randint(1,10,(3,2,4))
a

array([[[6, 2, 2, 4],
        [5, 6, 4, 9]],

       [[7, 3, 7, 5],
        [2, 6, 6, 7]],

       [[6, 8, 7, 6],
        [3, 1, 9, 8]]])

## 加权平均分

In [1]:
import numpy as np

arr = np.array([8, 8, 9, 7])
np.average(arr, weights=[1, 2, 3, 4])

7.9

## When 0 Then ?x2x4=2x4
#### axis=0时,表示按最外层数组 操作运算,就是按照3组
    此时就是把3组数组对位相加,形成2行4列的数组相加结果.

In [3]:
a.sum(axis=0)

array([[19, 13, 16, 15],
       [10, 13, 19, 24]])

## When 1 Then 3x?x4=3x4
#### axis=1时,表示按第二层数组 操作运算,就是按照2行操作
    此时就是把2行相加,形成3组4列的数组相加结果.

In [4]:
a.sum(axis=1)

array([[11,  8,  6, 13],
       [ 9,  9, 13, 12],
       [ 9,  9, 16, 14]])

## When 2 Then 3x2x? =3x2
#### axis=2时,表示按第三层数组 操作运算,就是按照4列操作
    此时就是把4列相加,形成3组2行的数组相加结果.

In [5]:
a.sum(axis=2)

array([[14, 24],
       [22, 21],
       [27, 21]])

# When (1,2) Then 3x?x?=3
#### axis=(1,2) ,表示按第2层 2行相加后,得到3组4列数组,再按第3层 4列相加,3个组的数字.

In [6]:
a.sum(axis=(1,2))

array([38, 43, 48])

## 额外学习 4维数组 的axis=0时相加

In [7]:
ax=np.random.randint(1,10,(2,3,4,5))
ax

array([[[[9, 5, 4, 2, 1],
         [6, 8, 1, 7, 4],
         [3, 9, 6, 9, 4],
         [1, 3, 1, 8, 3]],

        [[1, 7, 8, 1, 5],
         [6, 6, 8, 5, 2],
         [3, 7, 5, 5, 2],
         [4, 3, 4, 2, 3]],

        [[3, 2, 8, 3, 3],
         [1, 4, 4, 8, 6],
         [4, 5, 4, 4, 2],
         [6, 4, 7, 6, 5]]],


       [[[9, 5, 3, 8, 6],
         [9, 5, 5, 9, 1],
         [6, 1, 8, 5, 5],
         [7, 6, 3, 4, 9]],

        [[6, 8, 7, 5, 6],
         [3, 3, 1, 9, 3],
         [2, 9, 3, 9, 8],
         [5, 2, 7, 9, 7]],

        [[6, 1, 9, 1, 1],
         [9, 8, 8, 3, 3],
         [8, 6, 4, 9, 3],
         [4, 7, 9, 9, 2]]]])

In [8]:
ax.sum(axis=0)

array([[[18, 10,  7, 10,  7],
        [15, 13,  6, 16,  5],
        [ 9, 10, 14, 14,  9],
        [ 8,  9,  4, 12, 12]],

       [[ 7, 15, 15,  6, 11],
        [ 9,  9,  9, 14,  5],
        [ 5, 16,  8, 14, 10],
        [ 9,  5, 11, 11, 10]],

       [[ 9,  3, 17,  4,  4],
        [10, 12, 12, 11,  9],
        [12, 11,  8, 13,  5],
        [10, 11, 16, 15,  7]]])

In [13]:
x=np.random.randint(1,10,(2,4))
x

array([[4, 8, 5, 5],
       [1, 8, 3, 1]])