### 掩码_numpy 的ndarry掩码

掩码技术(mask)

  原理:

  1,nd(1,2,3,4)  一行ndarry数据

  2,nd[[True,False, False, True]] 用布尔值做掩码尺

  3,nd(1,4) 得出结果

#### 掩码的与或非的使用

  #### 使用实例及机制:

    1,nd[(nd>1)&(nd<3)]

    2,其中nd>1和nd<3会得出一个 ndarry对象 如:array([ True,  True, False]) 其结果就是掩码尺

    3,nd>1和nd<3 的运算规则遵循 numpy的广播机制

    4,可以统计nd>1得出的个数 :

      np.sum(nd>1)

      np.count_nonzero(nd>1) #统计非0数值的方法

    5,最终通过掩码尺返回nd数组里需要掩码的数值,而现实需要的数值

      掩码里只能使用位运算符

||位运算符号|逻辑运算符|
|-|-|-|
|与|&|and|
|或||||
|非|~|not|


  #### 位运算符机制:

      1—(nd>1) & (nd<3) 注意圆括号必须写 

    2—(array([False,  True,  True]))&(array([ True,  True, False]))

       注意位运算符等级优先关系运算符>,<,!=

    3—&按照对应位置,逐个运算比较得出返回数组结果

        结果:array([False,  True, False]) 

  #### 逻辑运算符机制:

    相对位运算符按一位位运算,而是整体比较返回一个布尔结果

In [2]:
import numpy as np
import pandas as pd

### 掩码技术原理

In [3]:
x=[1,2,3]
nd1=np.array(x)#创建ndarray方法
nd1

array([1, 2, 3])

#### 用布尔值数组做掩码尺

In [5]:
nd1[[ True,  True, False]]

array([1, 2])

#### 同理 nd1<3 能得出布尔值数组

In [6]:
nd1<3

array([ True,  True, False])

#### 所以可以套用关系算式做掩码

In [8]:
nd1[nd1<3]

array([1, 2])

### 掩码的与或非的使用

In [9]:
nd1[(nd1>1)&(nd1<3)] #注意圆括号,因为位运算符号比关系运算符号等级优先

array([2])

### 用统计函数统计关系算式里的True值

In [13]:
np.sum(nd1>1) #统计True的和,因为False为0,所以True的和为True的个数

2

In [12]:
np.count_nonzero(nd1>1) #统计非0数值的方法

2